name: Code Quality Analysis

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  sonarcloud:
    name: SonarCloud 分析
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for better analysis

      # Java プロジェクト用
      - name: Set up JDK 17 (Java プロジェクト用)
        if: hashFiles('**/pom.xml') != '' || hashFiles('**/*.gradle') != ''
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Node.js プロジェクト用
      - name: Set up Node.js (Node.js プロジェクト用)
        if: hashFiles('**/package.json') != ''
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Python プロジェクト用
      - name: Set up Python (Python プロジェクト用)
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Maven ビルド（カバレッジ含む）
      - name: Build with Maven (Java)
        if: hashFiles('**/pom.xml') != ''
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }} \
            -Dsonar.organization=${{ github.repository_owner }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Gradle ビルド（カバレッジ含む）
      - name: Build with Gradle (Java)
        if: hashFiles('**/*.gradle') != ''
        run: |
          ./gradlew build sonar \
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }} \
            -Dsonar.organization=${{ github.repository_owner }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # Node.js テスト & カバレッジ
      - name: Run tests (Node.js)
        if: hashFiles('**/package.json') != ''
        run: |
          npm ci
          npm test -- --coverage

      # SonarCloud スキャン (Node.js)
      - name: SonarCloud Scan (Node.js)
        if: hashFiles('**/package.json') != ''
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Python テスト & カバレッジ
      - name: Run tests (Python)
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
          pytest --cov=. --cov-report=xml

      # SonarCloud スキャン (Python)
      - name: SonarCloud Scan (Python)
        if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Comment on PR (品質ゲート失敗時)
        if: failure() && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const sonarUrl = `https://sonarcloud.io/dashboard?id=${{ github.repository_owner }}_${{ github.event.repository.name }}`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🔴 コード品質チェック失敗

            **SonarCloudの品質ゲートに合格しませんでした！**

            ### 確認方法
            [SonarCloud ダッシュボードを確認 →](${sonarUrl})

            ### よくある品質問題

            #### 1. コードカバレッジ不足
            - **基準**: 80% 以上
            - **対処**: テストケースを追加してください

            #### 2. コードスメル（Code Smells）
            - **問題**: 保守性の低いコード
            - **対処**: リファクタリングが必要です

            #### 3. バグ（Bugs）
            - **問題**: 潜在的なバグが検出されました
            - **対処**: 指摘された箇所を修正してください

            #### 4. セキュリティホットスポット（Security Hotspots）
            - **問題**: セキュリティリスクのある実装
            - **対処**: 安全な実装に変更してください

            #### 5. 重複コード（Duplications）
            - **基準**: 3% 以下
            - **対処**: 共通処理を関数/クラスに抽出してください

            ### 品質ゲート基準（デフォルト）

            | 項目 | 基準 |
            |------|------|
            | カバレッジ | ≥ 80% |
            | 重複率 | ≤ 3% |
            | 新規バグ | 0 |
            | 新規脆弱性 | 0 |
            | セキュリティホットスポット | レビュー済み |
            | 技術的負債 | ≤ 5% |

            ### 対処手順

            1. **SonarCloud ダッシュボードを確認**
               - 上記のリンクからアクセス
               - "Issues" タブで問題を確認

            2. **優先度順に修正**
               - 🔴 Blocker → 🟠 Critical → 🟡 Major → 🔵 Minor

            3. **修正後、再プッシュ**
               - CI が自動的に再実行されます

            ### 参考資料
            - [SonarCloud Documentation](https://docs.sonarcloud.io/)
            - [Clean Code Guide](https://www.sonarsource.com/resources/white-papers/clean-code/)
            `
            })

  spotbugs:
    name: SpotBugs 静的解析 (Java)
    runs-on: ubuntu-latest
    if: hashFiles('**/pom.xml') != '' || hashFiles('**/*.gradle') != ''
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Maven プロジェクト
      - name: Run SpotBugs (Maven)
        if: hashFiles('**/pom.xml') != ''
        run: mvn compile spotbugs:check

      # Gradle プロジェクト
      - name: Run SpotBugs (Gradle)
        if: hashFiles('**/*.gradle') != ''
        run: ./gradlew spotbugsMain

      - name: Upload SpotBugs Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-report
          path: |
            **/spotbugsXml.xml
            **/spotbugs.html

  pmd:
    name: PMD 静的解析 (Java)
    runs-on: ubuntu-latest
    if: hashFiles('**/pom.xml') != '' || hashFiles('**/*.gradle') != ''
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Maven プロジェクト
      - name: Run PMD (Maven)
        if: hashFiles('**/pom.xml') != ''
        run: mvn pmd:check

      # Gradle プロジェクト
      - name: Run PMD (Gradle)
        if: hashFiles('**/*.gradle') != ''
        run: ./gradlew pmdMain

      - name: Upload PMD Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-report
          path: |
            **/pmd.xml
            **/pmd.html

  eslint:
    name: ESLint 静的解析 (Node.js)
    runs-on: ubuntu-latest
    if: hashFiles('**/package.json') != ''
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npm run lint
        continue-on-error: true

      - name: Upload ESLint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.json

  pylint:
    name: Pylint 静的解析 (Python)
    runs-on: ubuntu-latest
    if: hashFiles('**/requirements.txt') != '' || hashFiles('**/pyproject.toml') != ''
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pylint

      - name: Run Pylint
        run: pylint **/*.py --exit-zero --output-format=json > pylint-report.json

      - name: Upload Pylint Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pylint-report
          path: pylint-report.json

  quality-summary:
    name: コード品質結果サマリー
    runs-on: ubuntu-latest
    needs: [sonarcloud, spotbugs, pmd, eslint, pylint]
    if: always()
    
    steps:
      - name: Create Summary
        uses: actions/github-script@v7
        with:
          script: |
            const sonarResult = '${{ needs.sonarcloud.result }}';
            const spotbugsResult = '${{ needs.spotbugs.result }}';
            const pmdResult = '${{ needs.pmd.result }}';
            const eslintResult = '${{ needs.eslint.result }}';
            const pylintResult = '${{ needs.pylint.result }}';
            
            let summary = '# 📊 コード品質分析結果\n\n';
            summary += '| 分析ツール | 結果 |\n';
            summary += '|-----------|------|\n';
            
            if (sonarResult !== 'skipped') {
              summary += `| SonarCloud | ${sonarResult === 'success' ? '✅ 合格' : '❌ 失敗'} |\n`;
            }
            if (spotbugsResult !== 'skipped') {
              summary += `| SpotBugs | ${spotbugsResult === 'success' ? '✅ 合格' : '❌ 失敗'} |\n`;
            }
            if (pmdResult !== 'skipped') {
              summary += `| PMD | ${pmdResult === 'success' ? '✅ 合格' : '❌ 失敗'} |\n`;
            }
            if (eslintResult !== 'skipped') {
              summary += `| ESLint | ${eslintResult === 'success' ? '✅ 合格' : '❌ 失敗'} |\n`;
            }
            if (pylintResult !== 'skipped') {
              summary += `| Pylint | ${pylintResult === 'success' ? '✅ 合格' : '❌ 失敗'} |\n`;
            }
            
            summary += '\n';
            
            const allSuccess = [sonarResult, spotbugsResult, pmdResult, eslintResult, pylintResult]
              .filter(r => r !== 'skipped')
              .every(r => r === 'success');
            
            if (allSuccess) {
              summary += '✅ **すべてのコード品質チェックが合格しました！**\n';
            } else {
              summary += '⚠️ **一部のコード品質チェックに失敗しました。レポートを確認してください。**\n';
            }
            
            core.summary.addRaw(summary);
            await core.summary.write();
